# Formules {#sec-formulas}

::: {.callout-tip title="Tip for HTML Version of Document"}
To copy a formula to MS Word, right-click on the formula and choose 'Copy to clipboard ... MathML Code. Then use CTRL/CMD+V to paste the formula.

To copy a formula to an RMarkdown document, right-click on the formula and choose 'Copy to clipboard ... TeX Commands'. In RStudio Visual Markdown Editor choose Insert ... Latex Math ... Display Math and then CTRL/CMD+V to paste the formula.
:::

## Covariance and Correlation

(Sample) Covariance

$$cov(x,y) = \frac{\sum (x_{i} - \bar{x})(y_{i} - \bar{y})}{n-1}$$

Pearson Correlation

$$r = \frac{cov(x,y)}{SD(x) * SD(y)}$$

## Linear Regression

Linear Regression Equation

$$y_{i} = b_{0} + b_{1}x_{1i} + b_{2}x_{2i} + ... + b_{k}x_{ki} + \epsilon_{i}$$

Simple Linear Regression: Slope

$$b_{1} = \frac{\sum(x_{i} - \bar{x})(y_{i} - \bar{y})}{\sum(x_{i} - \bar{x})^2}$$

Simple Linear Regression: Intercept/Constant

$$b_{0} = \bar{y} - b_{1}\bar{x}$$

Regression Model with Interaction

$$y = b_{0} + b_{1}x_{1} + b_{2}x_{2} + b_{3}(x_{1}x_{2}) + \epsilon$$

Marginal Effects in Interaction Model

$$b_{1} + (x2 * b_{3})$$ $$b_{2} + (x1 * b_{3})$$

t-test for regression coefficients

$$t = \frac{b}{SE_{b}}$$

Confidence Interval: Coefficient

$$CI = b \pm (t_{df} * SE)$$

Regression Sum of Squares (Also called: Model Sum of Squares)

$$SS_{Regression} = \sum(\hat{y} - \bar{y})^2$$

Residual Sum of Squares

$$SS_{Residual} = \sum(y_{i} - \hat{y})^2$$

Total Sum of Squares

$$SS_{Total} = \sum(y_{i} - \bar{y})^2$$

R^2^

$$R^2 = \frac{SS_{Regression}}{SS_{Total}}$$

$$R^2 = 1 - \frac{SS_{Residual}}{SS_{Total}} $$

Mean Squares: Residual

$$MS_{Residual} = \frac{SS_{Residual}}{\textrm{df}_{Residual}}$$ $$\textrm{df}_{Residual} = n-k$$ Mean Squares: Regression Model

$$MS_{Model} = \frac{SS_{Regression}}{df_{Model}}$$

$$df_{Model} = k$$ F

$$F = \frac{MS_{Model}}{MS_{Residual}}$$

## Logistic Regression

Logistic Regression Model with Single Explanatory Variable

$$\textrm{log(Odds)} = b_0 + b_1x_{1i} + b_2x_{2i}...$$

$$P(Y_{i} = 1) = \frac{1}{1 + e^{-(b_{0} + b_{1}x_{1i})}}$$

Odds and Probabiilty

$$odds = \frac{p}{1 - p}$$

$$p = \frac{odds}{1 + odds}$$

Odds Ratio

$$e^{b}$$

z statistic

$$z = \frac{b}{se}$$

Likelihood Ratio

$$\chi^2 = (-2LL_{baseline}) - (-2LL_{new})$$

$$\textrm{df} = k_{new} - k_{baseline}$$

## Appendix: Critical Values of t-distribution

```{r}
#| echo: false
#| warning: false
#| message: false

library(rio)
library(kableExtra)
ttab <- import("data/t-table.xlsx")

kable(ttab, caption = "Critical Values of the t-distribution (Two-Tailed Test)") |> 
  kable_classic(full_width=F) 
  

  
```
